### ISSUE TITLE
Technical timestamps in metadata

### ISSUE THREAD

**Issue by moritzzimmer** [stroeer/tapir#112]
Many of the date fields (`last_edited`, `last_published`, `created`) vanished from the CMS lately. After discussing this internally, we should cleanup those fields.

In addition, we can and should decide on whether to enforce: https://linter.aip.dev/142/time-field-names

_Originally posted by @thisismana in https://github.com/stroeer/tapir/pull/111#discussion_r527551801_

**Comment by moritzzimmer** [comment]
see https://github.com/stroeer/apollo-livingdocs-server/issues/229

**Comment by bobaaaaa** [comment]
For now the FE only needs two dates:

* published (Veröffentlicht am)
* updated (Aktualisiert am)

**Comment by moritzzimmer** [comment]
fixed with #160
