### ISSUE TITLE
automate generation and addition of go code

### ISSUE THREAD

**Issue by harryurban** [stroeer/tapir#229]
# WHAT 
The process of adding go code to this repository should be automated.

# WHY
- Manual steps can be forgotten by devs
- Non-go devs should not be obliged to understand the realm of go, especially since go is not a native programming language in our team / project (there are actually very few devs that know and code go)

**Comment by moritzzimmer** [comment]
We could create a separate repo for generated go code (like google does for their APIs) and trigger a remote workflow from here like this: https://blog.marcnuri.com/triggering-github-actions-across-different-repositories
