### ISSUE TITLE
evaluate Buf Schema Registry (BSR)

### ISSUE THREAD

**Issue by moritzzimmer** [stroeer/tapir#278]
The [Buf Schema Registry (BSR)](https://docs.buf.build/bsr/introduction) could be an interesting enhancement to our toolchain:

> The BSR stores and manages Protobuf files as versioned modules, so that individuals and organizations can consume and publish their APIs easier than ever before. 

> The BSR comes with a browsable UI, dependency management, API validation and versioning, autogenerated documentation, and an extensible plugin system which enables remote code generation.

**Comment by bobaaaaa** [comment]
Do we have a consumer who needs the proto files? If so, this looks good. 👍

**Comment by bobaaaaa** [comment]
x-ref: #31
