### ISSUE TITLE
`make test` without node/node-legacy

### ISSUE THREAD

**Issue by bobaaaaa** [stroeer/tapir#324]
https://github.com/stroeer/tapir/blob/b03b09f56ef6d425fe3030a203dc2dfcfadc9598/Makefile#L79-L85

The `nvm use` command did not work on my machine. The root cause is that we need to run both checks in a different node version locally. This would work with `nvm`

**Comment by moritzzimmer** [comment]
@bobaaaaa can we close this/re-enable node checks?

**Comment by bobaaaaa** [comment]
Yes

**Comment by bobaaaaa** [comment]
closed with #492
