### ISSUE TITLE
⚠️ define future 3rd party integration inside of content stages

### ISSUE THREAD

**Issue by harryurban** [stroeer/tapir#54]
**possible blocker to get the new WebSectionPage into production**

e.g. stage with two editorial teasers, and an Ad on 3rd position, but maybe on 1st position tomorrow
e.g. inhouse teaser placements
e.g. widgets rendered as teasers (Google Maps widget, finance widget, news from other publishers,....)

**requirements engineering necessary**

**Comment by bobaaaaa** [comment]
@harryurban is this still relevant?
