### ISSUE TITLE
Metadata.publication_date?

### ISSUE THREAD

**Issue by moritzzimmer** [stroeer/tapir#8]
This seems like a bug - `publication_date` is part of the `fields` map.

**Comment by harryurban** [comment]
i moved it knowingly to all the other date fields, like `state` or `valid_from`

**Comment by harryurban** [comment]
but can be moved back, was just a proposal

**Comment by moritzzimmer** [comment]
`publication_date` had no impact on legal checking in the past (like `last_modified_date`)
