### ISSUE TITLE
Add documentation generator

### ISSUE THREAD

**Issue by bobaaaaa** [stroeer/tapir#84]
At some point we need some documentation for some code conventions. Examples:

- list of valid `BodyNode.type` strings
- list of valid `fields` keys

### Requirements

- generate HTML documentation based on code comments
- deploy & host to GitHub pages (latest published version)

### Links

https://github.com/pseudomuto/protoc-gen-doc

### Future

- How do we deal with API changes? Versioned documentation?

**Comment by moritzzimmer** [comment]
We (@thisismana, @bobaaaaa, @harryurban and @moritzzimmer) to first invest time in documenting our proto messages and gRPC APIs. Generating a HTML documentation in addition to the documented proto files might follow later.
